# -*- coding: utf-8 -*-
"""Neural network to find malaria.ipynb

Automatically generated by Colaboratory. 

https://colab.research.google.com
"""

import tensorflow
import tensorflow_datasets as tfds

malaria, info = tfds.load(name="malaria",
                          split="train",
                          with_info=True)

malaria

info

malaria = malaria.shuffle(20000).prefetch(tensorflow.data.experimental.AUTOTUNE)

malaria