# -*- coding: utf-8 -*-
"""Neural network to find malaria.ipynb

Automatically generated by Colaboratory.
  

https://colab.research.google.com
"""

import tensorflow
import tensorflow_datasets as tfds

malaria, info = tfds.load(name="malaria",
                          split="train",
                          with_info=True)

malaria

info

malaria = malaria.shuffle(20000).prefetch(tensorflow.data.experimental.AUTOTUNE)

malaria

import matplotlib.pyplot as pyplot

pyplot.figure(figsize=(30, 30))

num_of_images = 8

for index, feature in enumerate(malaria.take(num_of_images)):

  image = feature["image"].numpy()

  label = feature["label"].numpy()

  pyplot.subplot(4, 2, index + 1)

  pyplot.title("Class: " + str(label))

  pyplot.imshow(image)

pyplot.show()